defmodule Jack.Engine do
  @moduledoc """
  Effects the actual compilation output. Gets its input from a
  JackTokenizer and emits its parsed structure into an output file/stream. The
  output is generated by a series of compilexxx() routines, one for every syntactic
  element xxx of the Jack grammar. The contract between these routines is that each
  compilexxx() routine should read the syntactic construct xxx from the input,
  advance() the tokenizer exactly beyond xxx, and output the parsing of xxx. Thus,
  compilexxx() may only be called if indeed xxx is the next syntactic element of the
  input.

  CompileClass            Compiles a complete class.
  CompileClassVarDec      Compiles a static declaration or a field declaration.
  CompileSubroutine       Compiles a complete method, function, or constructor.
  compileParameterList    Compiles a (possibly empty) parameter list, not including the enclosing ‘‘()’’.
  compileVarDec           Compiles a var declaration.
  compileStatements       Compiles a sequence of statements, not including the enclosing ‘‘{}’’.
  compileDo               Compiles a do statement.
  compileLet              Compiles a let statement.
  compileWhile            Compiles a while statement.
  compileReturn           Compiles a return statement.
  compileIf               Compiles an if statement, possibly with a trailing else clause.
  CompileExpression       Compiles an expression.
  CompileTerm             Compiles a term. This routine is faced with a slight difficulty
                            when trying to decide between some of the alternative parsing
                            rules. Specifically, if the current token is an identifier, the routine
                            must distinguish between a variable, an array entry, and a
                            subroutine call. A single lookahead token, which may be one
                            of ‘‘[’’, ‘‘(’’, or ‘‘.’’ suffices to distinguish between the three possibilities.
                            Any other token is not part of this term and should not be advanced over.
  CompileExpressionList   Compiles a (possibly empty) comma-separated list of expressions.
  """
end
